apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: raas/payment-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_DB_URL
              value: "jdbc:postgresql://postgres:5432/payment"
            - name: PAYMENT_DB_USER
              value: "payment"
            - name: PAYMENT_DB_PASSWORD
              value: "payment"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: STRIPE_API_KEY
              value: ""
