apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  namespace: raas
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: raas/review-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REVIEW_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: raas-config
                  key: REVIEW_DB_URL
            - name: REVIEW_DB_USER
              value: "review"
            - name: REVIEW_DB_PASSWORD
              value: "review"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: raas-config
                  key: KAFKA_BROKER
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: raas
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
  selector:
    app: review-service
