apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deployment
  labels:
    app: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: raas/media-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET
              value: "raas-media-bucket"
            - name: KAFKA_BROKERS
              value: "kafka:9092"