apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-deployment
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: raas/booking-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: PG_URI
              value: "postgres://user:password@postgres:5432/raas"
            - name: REDIS_URL
              value: "redis:6379"
            - name: KAFKA_BROKERS
              value: "kafka:9092"